import re

from app.models.code_value import CodeValue
from app.services.db_get_or_create import db_get_or_create


def SU_codevalues_cs4003(db):
    """ Codeset 4003: Frequency """

    # format: (display, description)
    code_values = (
        ('qHS', 'daily at bedtime'),
        ('qSatSun', 'every Saturday and Sunday'),
        ('q2h', 'every 2 hours'),
        ('7 times a day', 'seven times a day'),
        ('q2week interval', 'every 2 weeks'),
        ('qdaily after food', 'daily after food'),
        ('q2day interval', 'every 2 days'),
        ('BID', 'twice a day'),
        ('qdaily', 'daily'),
        ('BID before food', 'twice a day before food'),
        ('BID after food', 'twice a day after food'),
        ('qMonWedThuSatSun', 'every Monday, Wednesday, Thursday, Saturday and Sunday'),
        ('q12h interval', 'every 12 hours'),
        ('q18h', 'every 18 hours'),
        ('q1h interval', 'every 1 hour'),
        ('q24h', 'every 24 hours'),
        ('q2h interval', 'every 2 hours'),
        ('q36h', 'every 36 hours'),
        ('q3h interval', 'every 3 hours'),
        ('8 times a day', 'eight times a day'),
        ('q48h', 'every 48 hours'),
        ('q4h interval', 'every 4 hours'),
        ('6 times a day', 'six times a day'),
        ('q4h while awake', 'every 4 hours while awake'),
        ('5 times a day', 'five times a day'),
        ('q6h interval', 'every 6 hours'),
        ('q72h', 'every 72 hours'),
        ('q8h interval', 'every 8 hours'),
        ('q96h interval', 'every 96 hours'),
        ('qAM', 'daily in the morning'),
        ('qdaily with food', 'daily with food'),
        ('TID before food', 'three times a day before food'),
        ('TID after food', 'three times a day after food'),
        ('q10min', 'every 10 minutes'),
        ('q15min', 'every 15 minutes'),
        ('q20min', 'every 20 minutes'),
        ('q30min', 'every 30 minutes'),
        ('q5min', 'every 5 minutes'),
        ('qMonFri', 'every Monday and Friday'),
        ('qMonThu', 'every Monday and Thursday'),
        ('q3day interval', 'every 3 days'),
        ('q4day interval', 'every 4 days'),
        ('q5day interval', 'every 5 days'),
        ('qweek interval', 'every 168 hours'),
        ('qTueThu', 'every Tuesday and Thursday'),
        ('qPM', 'daily in the evening'),
        ('q365day interval', 'every 365 days'),
        ('qMonWedFri', 'every Monday, Wednesday and Friday'),
        ('QID before food and bedtime', 'four times a day before food and at bedtime'),
        ('TID with food', 'three times a day with food'),
        ('BID with food', 'twice a day with food'),
        ('q90day interval', 'every 90 days'),
        ('q180day interval', 'every 180 days'),
        ('QID after food and bedtime', 'four times a day after food and at bedtime'),
        ('q30day interval', 'every 30 days'),
        ('TID', 'three times a day'),
        ('qdaily before food', 'daily before food'),
        ('on call to OR', 'on call to the operating room'),
        ('as directed', 'as directed'),
        ('qWedSat', 'every Wednesday and Saturday'),
        ('qMonWedFriSat', 'every Monday, Wednesday, Friday and Saturday'),
        ('qWedSun', 'every Wednesday and Sunday'),
        ('qTueSat', 'every Tuesday and Saturday'),
        ('qTueFri', 'every Tuesday and Friday'),
        ('qTueThuSat', 'every Tuesday, Thursday and Saturday'),
        ('qTue', 'every week on Tuesday'),
        ('qWed', 'every week on Wednesday'),
        ('qThu', 'every week on Thursday'),
        ('qFri', 'every week on Friday'),
        ('qMon', 'every week on Monday'),
        ('once oncology', 'one time'),
        ('QID', 'four times a day'),
        ('TID with snacks', 'three times a day with snacks'),
        ('QID with food and bedtime snack', 'four times a day with food and bedtime snack'),
        ('pre-op', 'prior to operation'),
        ('q2h while awake', 'every 2 hours while awake'),
        ('q8h', 'every 8 hours'),
        ('q6h while awake', 'every 6 hours while awake'),
        ('q8week interval', 'every 8 weeks'),
        ('q3h', 'every 3 hours'),
        ('120 min pre-op', '120 minutes prior to operation'),
        ('q4min', 'every 4 minutes'),
        ('q45min', 'every 45 minutes'),
        ('qTueThuSun', 'every Tuesday, Thursday and Sunday'),
        ('BIDWedThuFri', 'twice a day every Wednesday, Thursday and Friday'),
        ('q6day interval', 'every 6 days'),
        ('qTueThuSatSun', 'every Tuesday, Thursday, Saturday and Sunday'),
        ('BIDTueWedThu', 'twice a day every Tuesday, Wednesday and Thursday'),
        ('BIDSunMonTues', 'twice a day every Sunday, Monday and Tuesday'),
        ('60 min pre-op', '60 minutes prior to operation'),
        ('pre-procedure', 'prior to procedure'),
        ('q1min', 'every 1 minute'),
        ('q6min', 'every 6 minutes'),
        ('q7min', 'every 7 minutes'),
        ('BIDFriSatSun', 'twice a day every Friday, Saturday and Sunday'),
        ('q1h', 'every 1 hour'),
        ('q4h', 'every 4 hours'),
        ('BIDThuFriSat', 'twice a day every Thursday, Friday and Saturday'),
        ('BIDSatSunMon', 'twice a day every Saturday, Sunday and Monday'),
        ('30 min pre-op', '30 minutes prior to operation'),
        ('90 min pre-op', '90 minutes prior to operation'),
        ('q28day interval', 'every 28 days'),
        ('q60day interval', 'every 60 days'),
        ('q3min', 'every 3 minutes'),
        ('q8min', 'every 8 minutes'),
        ('q9min', 'every 9 minutes'),
        ('qMonTueWedThuFri', 'every Monday, Tuesday, Wednesday, Thursday and Friday'),
        ('qMonTueThuFriSun', 'every Monday, Tuesday,Thursday, Friday and Sunday'),
        ('q3h while awake', 'every 3 hours while awake'),
        ('q1h while awake', 'every 1 hour while awake'),
        ('q6h', 'every 6 hours'),
        ('q12h', 'every 12 hours'),
        ('qSat', 'every week on Saturday'),
        ('qSun', 'every week on Sunday'),
        ('qThuSun', 'every Thursday and Sunday'),
        ('qMonWedSat', 'every Monday, Wednesday and Saturday'),
        ('qMonWedFriSun', 'every Monday, Wednesday, Friday and Sunday'),
        ('BID with snacks', 'twice a day with snacks'),
        ('qdaily with supper', 'daily with supper'),
        ('BIDMonTueWed', 'twice a day every Monday, Tuesday and Wednesday'),
        ('prior to discharge', 'prior to discharge'),
        ('q2min', 'every 2 minutes'),
        ('q90min', 'every 90 minutes'),
        ('qdaily with breakfast', 'daily with breakfast'),
        ('qdaily after breakfast', 'daily after breakfast'),
        ('qdaily before breakfast', 'daily before breakfast'),
        ('qdaily with lunch', 'daily with lunch'),
        ('qdaily after lunch', 'daily after lunch'),
        ('qdaily before lunch', 'daily before lunch'),
        ('qdaily after supper', 'daily after supper'),
        ('qdaily before supper', 'daily before supper'),
        ('q2day', 'every 2 days'),
        ('q3day', 'every 3 days'),
        ('qweek', 'every 1 week'),
        ('q2week', 'every 2 weeks'),
        ('q3week', 'every 3 weeks'),
        ('q4week', 'every 4 weeks'),
        ('q12week', 'every 12 weeks'),
        ('q8week', 'every 8 weeks'),
        ('q12h oncology', 'every 12 hours'),
        ('q8h oncology', 'every 8 hours'),
        ('q6h oncology', 'every 6 hours'),
        ('q4h oncology', 'every 4 hours'),
        ('q3h oncology', 'every 3 hours'),
        ('q120day interval', 'every 120 days'),
        ('q90day', 'every 90 days'),
        ('q180day', 'every 180 days'),
        ('q6week', 'every 6 weeks'),
        ('qMonTueWedThuFriSat', 'every Mon, Tue, Wed, Thu, Fri and Sat'),
        ('qTueWedThuFriSatSun', 'every Tue, Wed, Thu, Fri, Sat and Sun'),
        ('qMonWedThuFriSatSun', 'every Mon, Wed, Thu, Fri, Sat and Sun'),
        ('qMonTueThuFriSatSun', 'every Mon, Tue, Thu, Fri, Sat and Sun'),
        ('qMonTueWedFriSatSun', 'every Mon, Tue, Wed, Fri, Sat and Sun'),
        ('qMonTueWedThuSatSun', 'every Mon, Tue, Wed, Thu, Sat and Sun'),
        ('qMonTueWedThuFriSun', 'every Mon, Tue, Wed, Thu, Fri and Sun'),
        ('BIDMonThu', 'twice a day every Monday and Thursday'),
        ('BIDMonWedFri', 'twice a day every Monday, Wednesday and Friday'),
        ('q16h', 'every 16 hours'),
        ('q10day interval', 'every 10 days'),
        ('q10h oncology', 'every 10 hours'),
        ('q11h oncology', 'every 11 hours'),
        ('qMonWed', 'every Monday and Wednesday'),
        ('qMonSat', 'every Monday and Saturday'),
        ('qTueSun', 'every Tuesday and Sunday'),
        ('qWedFri', 'every Wednesday and Friday'),
        ('qThuSat', 'every Thursday and Saturday'),
        ('qFriSun', 'every Friday and Sunday'),
        ('qMonThuSat', 'every Monday, Thursday, and Saturday'),
        ('qTueFriSun', 'every Tuesday, Friday, and Sunday'),
        ('qWedFriSun', 'every Wednesday, Friday, and Sunday'),
        ('qMonWedThuSat', 'every Monday, Wednesday, Thursday, and Saturday'),
        ('qTueThuFriSun', 'every Tuesday, Thursday, Friday, and Sunday'),
        ('hemodialysis', 'give in hemodialysis unit'),
        ('qTueThuFri', 'every Tuesday, Thursday and Friday'),
        ('qweek oncology', 'every 1 week'),
        ('q2week oncology', 'every 2 weeks'),
        ('hemodialysis qweek', 'give in hemodialysis every 1 week'),
        ('hemodialysis 3 times/week', 'give in hemodialysis 3 times every 1 week'),
        ('hemodialysis q2week', 'give in hemodialysis every 2 weeks'),
        ('hemodialysis q4week', 'give in hemodialysis every 4 weeks'),
        ('qTue 1100', 'every week on Tuesday 1100h'),
        ('qFriSat', 'every Friday and Saturday'),
        ('q1h oncology', 'every 1 hour'),
        ('q16day', 'every 16 days'),
        ('q2h oncology', 'every 2 hours'),
        ('q17day', 'every 17 days'),
        ('BIDSatSun', 'twice a day every Saturday and Sunday'),
        ('hemodialysis q8week', 'give in hemodialysis every 8 weeks'),
        ('q5week', 'every 5 weeks'),
        ('once', 'one time'),
        ('IQHEALTH.MEDICATIONS', 'IQHEALTH.MEDICATIONS'),
        ('hemodialysis 2 times/week', 'give in hemodialysis 2 times every 1 week'),
    )
    with db.session() as session:
        for display, description in code_values:
            db_get_or_create(
                session,
                CodeValue,
                code_set = 4003,
                definition = description,
                description = description,
                display = display,
                display_key = re.sub('[^0-9a-zA-Z]+', '', display).upper()  # remove non-alphanumeric characters
            )


if __name__ == '__main__':
    SU_codevalues_cs4003()
