"""test3

Revision ID: 69e704b84bc1
Revises: ea1ec6e7d994
Create Date: 2024-11-02 00:00:38.255342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e704b84bc1'
down_revision = 'ea1ec6e7d994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_set', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['code_set'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_set', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
