"""user name nullable

Revision ID: 7082df4e06f7
Revises: a6d7bc021053
Create Date: 2024-11-02 20:42:41.510751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7082df4e06f7'
down_revision = 'a6d7bc021053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_name_last_key'), ['name_last_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name_last_key'))

    # ### end Alembic commands ###
