"""initial

Revision ID: ea1ec6e7d994
Revises: 
Create Date: 2024-11-01 23:24:12.683450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1ec6e7d994'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_set',
    sa.Column('code_set', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('active_ind', sa.Boolean(), nullable=False),
    sa.Column('add_access_ind', sa.Boolean(), nullable=True),
    sa.Column('alias_dup_ind', sa.Boolean(), nullable=True),
    sa.Column('cache_ind', sa.Boolean(), nullable=True),
    sa.Column('meaning_dup_ind', sa.Boolean(), nullable=True),
    sa.Column('change_access_ind', sa.Boolean(), nullable=True),
    sa.Column('code_set_hits', sa.Integer(), nullable=True),
    sa.Column('code_value_cnt', sa.Integer(), nullable=True),
    sa.Column('contributor', sa.String(length=20), nullable=True),
    sa.Column('definition', sa.String(length=500), nullable=True),
    sa.Column('definition_dup_ind', sa.Boolean(), nullable=True),
    sa.Column('del_access_ind', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.Column('display', sa.String(length=40), nullable=False),
    sa.Column('display_dup_ind', sa.Boolean(), nullable=True),
    sa.Column('display_key', sa.String(length=40), nullable=True),
    sa.Column('display_key_dup_ind', sa.Boolean(), nullable=True),
    sa.Column('domain_code_set', sa.Integer(), nullable=True),
    sa.Column('domain_qualifier_ind', sa.Boolean(), nullable=True),
    sa.Column('extension_ind', sa.Boolean(), nullable=True),
    sa.Column('inq_access_ind', sa.Boolean(), nullable=True),
    sa.Column('inst_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_module', sa.String(length=20), nullable=True),
    sa.Column('table_name', sa.String(length=32), nullable=True),
    sa.Column('txn_id_text', sa.String(length=200), nullable=True),
    sa.Column('updt_applctx', sa.BigInteger(), nullable=True),
    sa.Column('updt_cnt', sa.Integer(), nullable=True),
    sa.Column('updt_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('updt_id', sa.BigInteger(), nullable=True),
    sa.Column('updt_task', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('code_set'),
    sa.UniqueConstraint('code_set')
    )
    with op.batch_alter_table('code_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_set_display'), ['display'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_set_display_key'), ['display_key'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('password_expiry_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('name_first', sa.String(length=200), nullable=True),
    sa.Column('name_first_key', sa.String(length=100), nullable=True),
    sa.Column('name_full_formatted', sa.String(length=100), nullable=True),
    sa.Column('name_last', sa.String(length=200), nullable=True),
    sa.Column('name_last_key', sa.String(length=100), nullable=True),
    sa.Column('name_middle', sa.String(length=200), nullable=True),
    sa.Column('name_middle_key', sa.String(length=100), nullable=True),
    sa.Column('active_status_cd', sa.BigInteger(), nullable=True),
    sa.Column('active_status_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('active_status_prsnl_id', sa.BigInteger(), nullable=True),
    sa.Column('beg_effective_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('end_effective_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('create_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('create_prsnl_id', sa.BigInteger(), nullable=True),
    sa.Column('updt_applctx', sa.BigInteger(), nullable=True),
    sa.Column('updt_cnt', sa.Integer(), nullable=True),
    sa.Column('updt_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('updt_id', sa.BigInteger(), nullable=True),
    sa.Column('updt_task', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name_first_key'), ['name_first_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name_middle_key'), ['name_middle_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_password'), ['password'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('code_value',
    sa.Column('code_value', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('active_ind', sa.Boolean(), nullable=True),
    sa.Column('active_type_cd', sa.BigInteger(), nullable=True),
    sa.Column('active_status_prsnl_id', sa.BigInteger(), nullable=True),
    sa.Column('begin_effective_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('end_effective_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('meaning', sa.String(length=12), nullable=True),
    sa.Column('cki', sa.String(length=255), nullable=True),
    sa.Column('code_set', sa.Integer(), nullable=True),
    sa.Column('collation_seq', sa.Integer(), nullable=True),
    sa.Column('concept_cki', sa.String(length=255), nullable=True),
    sa.Column('data_status_cd', sa.BigInteger(), nullable=True),
    sa.Column('data_status_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('data_status_prsnl_id', sa.BigInteger(), nullable=True),
    sa.Column('definition', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.Column('display', sa.String(length=40), nullable=True),
    sa.Column('display_key', sa.String(length=40), nullable=True),
    sa.Column('inactive_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('inst_id', sa.BigInteger(), nullable=True),
    sa.Column('txn_id_text', sa.String(length=200), nullable=True),
    sa.Column('updt_applctx', sa.BigInteger(), nullable=True),
    sa.Column('updt_cnt', sa.Integer(), nullable=True),
    sa.Column('updt_dt_tm', sa.DateTime(), nullable=True),
    sa.Column('updt_id', sa.BigInteger(), nullable=True),
    sa.Column('updt_task', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_set'], ['code_set.code_set'], ),
    sa.PrimaryKeyConstraint('code_value')
    )
    with op.batch_alter_table('code_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_value_display'), ['display'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_value_display_key'), ['display_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_value_display_key'))
        batch_op.drop_index(batch_op.f('ix_code_value_display'))

    op.drop_table('code_value')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_password'))
        batch_op.drop_index(batch_op.f('ix_users_name_middle_key'))
        batch_op.drop_index(batch_op.f('ix_users_name_first_key'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('code_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_set_display_key'))
        batch_op.drop_index(batch_op.f('ix_code_set_display'))

    op.drop_table('code_set')
    # ### end Alembic commands ###
