"""Create code_value table with sequence

Revision ID: eba2a3e53a0c
Revises: ec1d97cda95b
Create Date: 2024-10-31 23:34:25.667414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba2a3e53a0c'
down_revision = 'ec1d97cda95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_set', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['code_set'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_set', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
